<?php

/**
 * @file
 * Contains code for Toolbar test module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() for all forms.
 */
function toolbartest_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_permission_map = _toolbartest_unsafe_forms();
  if (!in_array($form_id, array_keys($form_permission_map))) {
    return;
  }

  $current_user = \Drupal::currentUser();
  if (
    !empty($form_permission_map[$form_id]) &&
    !$current_user->hasPermission($form_permission_map[$form_id])
  ) {
    $form['#validate'] = $form['#validate'] ?? [];
    array_unshift($form['#validate'], '_toolbartest_form_submit');
  }
}

/**
 * Validate handler to get back some (false?) sense of security.
 */
function _toolbartest_form_submit(&$form, FormStateInterface $form_state) {
  $form_state->setErrorByName('__none__', t('Permission denied.'));
}

/**
 * Returns runied form's id with the original required route perm.
 *
 * Some form's original route permission requirement is ruined by us.
 * To keep the toolbar test module's changes safe as much as possible, we'll
 * check in a custom form validation handler that the current user has the
 * original permission.
 *
 * @see \Drupal\toolbartest\Routing\RouteSubscriber.php
 */
function _toolbartest_unsafe_forms() {
  return [
    'block_settings_tray_form' => 'administer site configuration',
    'block_form' => 'administer site configuration',
    'block_delete_form' => 'administer site configuration',
    'cd_tools_dashboard_form' => 'administer modules',
    'comment_admin_overview' => 'administer comments',
    'language_admin_overview_form' => 'administer languages',
    'language_content_settings_form' => 'administer languages',
    'language_negotiation_configure_form' => 'administer languages',
    'system_modules' => 'administer modules',
    'system_regional_settings' => 'administer site configuration',
    'system_themes_admin_form' => 'administer themes',
  ];
}
