<?php

/**
 * @file
 * Contains code for Details test module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function details_toolbar() {
  $items['details_test'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Details'),
      '#url' => Url::fromRoute('system.site_information_settings'),
    ],
    '#weight' => 116,
  ];

  return $items;
}

/**
 * Implements hook_form_alter() for all forms.
 */
function details_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_permission_map = _details_unsafe_forms();
  if (!in_array($form_id, array_keys($form_permission_map))) {
    return;
  }

  $current_user = \Drupal::currentUser();
  if (
    !empty($form_permission_map[$form_id]) &&
    !$current_user->hasPermission($form_permission_map[$form_id])
  ) {
    $form['#validate'] = $form['#validate'] ?? [];
    array_unshift($form['#validate'], '_details_form_submit');
  }
}

/**
 * Validate handler to get back some (false?) sense of security.
 */
function _details_form_submit(&$form, FormStateInterface $form_state) {
  $form_state->setErrorByName('__none__', t('Permission denied.'));
}

/**
 * Returns runied form's id with the original required route perm.
 *
 * Some form's original route permission requirement is ruined by us.
 * To keep the test module's changes safe as much as possible, we'll
 * check in a custom form validation handler that the current user has the
 * original permission.
 *
 * @see \Drupal\details\Routing\RouteSubscriber.php
 */
function _details_unsafe_forms() {
  return [
    'system_site_information_settings' => 'administer site configuration',
  ];
}
